global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'seravie-app'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'supabase-metrics'
    static_configs:
      - targets: ['https://qgmffsrgfyphmuqvafdc.supabase.co']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alerts.yml'
