// Configuração declarativa de cada coleção do CMS, consumida pelo CollectionManager.
export const collectionConfigs = {
  posts: {
    table: 'posts',
    title: 'Jornal',
    subtitle: 'Artigos e novidades da Seravie.',
    orderColumn: 'created_at',
    newDefault: () => ({ slug: 'post-' + Date.now(), title: 'Novo post', published: false }),
    fields: [
      { key: 'title', label: 'Título', full: true },
      { key: 'slug', label: 'Slug (URL)' },
      { key: 'category', label: 'Categoria' },
      { key: 'excerpt', label: 'Resumo', type: 'textarea' },
      { key: 'body', label: 'Conteúdo', type: 'textarea', rows: 8 },
      { key: 'cover_image', label: 'Imagem de capa', type: 'image' },
      { key: 'author', label: 'Autor' },
      { key: 'tags', label: 'Tags', type: 'tags' },
      { key: 'seo_title', label: 'SEO — título' },
      { key: 'seo_description', label: 'SEO — descrição' },
      { key: 'published', label: 'Publicado', type: 'toggle' },
    ],
  },
  testimonials: {
    table: 'testimonials',
    title: 'Depoimentos',
    subtitle: 'O que clientes e parceiros dizem.',
    newDefault: () => ({ author_name: 'Nome', quote: 'Depoimento...', published: true }),
    fields: [
      { key: 'author_name', label: 'Nome' },
      { key: 'author_role', label: 'Cargo / contexto' },
      { key: 'quote', label: 'Depoimento', type: 'textarea', full: true },
      { key: 'avatar_url', label: 'Foto', type: 'image' },
      { key: 'rating', label: 'Nota (1–5)', type: 'number' },
      { key: 'published', label: 'Publicado', type: 'toggle' },
    ],
  },
  faqs: {
    table: 'faqs',
    title: 'Perguntas frequentes',
    subtitle: 'Dúvidas comuns dos clientes.',
    newDefault: () => ({ question: 'Pergunta?', answer: 'Resposta...', published: true }),
    fields: [
      { key: 'question', label: 'Pergunta', full: true },
      { key: 'answer', label: 'Resposta', type: 'textarea', full: true },
      { key: 'published', label: 'Publicado', type: 'toggle' },
    ],
  },
  team: {
    table: 'team_members',
    title: 'Equipe',
    subtitle: 'Pessoas por trás da Seravie.',
    newDefault: () => ({ name: 'Nome', published: true }),
    fields: [
      { key: 'name', label: 'Nome' },
      { key: 'role', label: 'Cargo' },
      { key: 'bio', label: 'Bio', type: 'textarea', full: true },
      { key: 'photo_url', label: 'Foto', type: 'image' },
      { key: 'instagram', label: 'Instagram (URL)' },
      { key: 'linkedin', label: 'LinkedIn (URL)' },
      { key: 'published', label: 'Publicado', type: 'toggle' },
    ],
  },
  pages: {
    table: 'pages',
    title: 'Páginas',
    subtitle: 'Páginas institucionais e legais (corpo de texto em breve).',
    orderColumn: 'created_at',
    newDefault: () => ({ slug: 'pagina-' + Date.now(), title: 'Nova página', published: false }),
    fields: [
      { key: 'title', label: 'Título', full: true },
      { key: 'slug', label: 'Slug (URL)' },
      { key: 'seo_title', label: 'SEO — título' },
      { key: 'seo_description', label: 'SEO — descrição', type: 'textarea', full: true },
      { key: 'published', label: 'Publicada', type: 'toggle' },
    ],
  },
  menus: {
    table: 'menu_items',
    title: 'Menus',
    subtitle: 'Itens de navegação do cabeçalho e rodapé.',
    newDefault: () => ({ label: 'Novo item', url: '#', location: 'header', published: true }),
    fields: [
      { key: 'label', label: 'Texto' },
      { key: 'url', label: 'Link (URL)' },
      { key: 'location', label: 'Local', type: 'select', options: ['header', 'footer'] },
      { key: 'published', label: 'Visível', type: 'toggle' },
    ],
  },
  process: {
    table: 'process_steps',
    title: 'Processo',
    subtitle: 'Etapas exibidas na seção “Nosso processo”.',
    newDefault: () => ({ title: 'Nova etapa', icon: 'spark', published: true }),
    fields: [
      { key: 'step_number', label: 'Número (ex.: 01)' },
      { key: 'title', label: 'Título' },
      { key: 'description', label: 'Descrição', type: 'textarea', full: true },
      { key: 'icon', label: 'Ícone', type: 'icon', full: true },
      { key: 'published', label: 'Publicada', type: 'toggle' },
    ],
  },
  segments: {
    table: 'segments',
    title: 'Segmentos',
    subtitle: 'Públicos exibidos em “Para quem criamos”.',
    newDefault: () => ({ title: 'Novo segmento', icon: 'leaf', published: true }),
    fields: [
      { key: 'title', label: 'Título' },
      { key: 'icon', label: 'Ícone', type: 'icon', full: true },
      { key: 'published', label: 'Publicado', type: 'toggle' },
    ],
  },
  translations: {
    table: 'translations',
    title: 'Traduções',
    subtitle: 'Textos de interface por idioma (PT/EN/ES).',
    orderColumn: 'key',
    newDefault: () => ({ namespace: 'common', key: 'nova.chave', locale: 'pt', value: '' }),
    fields: [
      { key: 'namespace', label: 'Namespace' },
      { key: 'key', label: 'Chave' },
      { key: 'locale', label: 'Idioma', type: 'select', options: ['pt', 'en', 'es'] },
      { key: 'value', label: 'Texto', type: 'textarea', full: true },
    ],
  },
}
